SELECT 
I.IMAGE_ID,
G.ID_INTERN,
I.TIMESTAMP,
B.BROTH_NAME,
TS.STRAIN_NAME,
SI.INHIBITION_BOOL

FROM Images I
LEFT JOIN Streptomyceten G ON I.GROUP_ID = G.ID_GROUP
LEFT JOIN Broth B ON I.BROTH_ID = B.BROTH_ID 
LEFT JOIN 'Strain-Inhibits' SI ON I.IMAGE_ID = SI.IMAGE_ID
LEFT JOIN Test_Strains TS ON SI.STRAIN_ID = TS.STRAIN_ID
WHERE SI.INHIBITION_BOOL NOT NULL
ORDER BY G.ID_INTERN, BROTH_NAME ASC;