/********************************************************************************
** Form generated from reading UI file 'MultiUploadDialog.ui'
**
** Created by: Qt User Interface Compiler version 5.12.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MULTIUPLOADDIALOG_H
#define UI_MULTIUPLOADDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_multiUpload
{
public:
    QDialogButtonBox *buttonBox;
    QGraphicsView *graphicsView;
    QGraphicsView *graphicsView_2;
    QGraphicsView *graphicsView_3;
    QGraphicsView *graphicsView_4;
    QLineEdit *line_groupID_group;
    QLineEdit *line_genome;
    QLabel *label_22;
    QLineEdit *line_spore_color;
    QLineEdit *line_internID;
    QLabel *label_27;
    QLabel *label_21;
    QLabel *label_24;
    QLabel *label_25;
    QCheckBox *checkBox_siderophore;
    QLabel *label_26;
    QLabel *label_18;
    QLineEdit *line_timestamp_group;
    QLabel *label_20;
    QLabel *label_23;
    QLineEdit *line_locality;
    QLineEdit *line_scientific;
    QLabel *label_5;
    QLineEdit *line_ID;
    QLabel *label_10;
    QLabel *label_8;
    QLabel *label_7;
    QLabel *label_6;
    QLineEdit *line_resolution_x;
    QLabel *label_9;
    QLineEdit *line_imgSize;
    QLineEdit *line_timestamp;
    QLineEdit *line_path;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *line_ID_2;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_15;
    QLineEdit *line_imgSize_2;
    QLineEdit *line_timestamp_2;
    QLineEdit *line_path_2;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_19;
    QLabel *label_28;
    QLineEdit *line_ID_3;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLineEdit *line_imgSize_3;
    QLineEdit *line_timestamp_3;
    QLineEdit *line_path_3;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLineEdit *line_ID_4;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLineEdit *line_imgSize_4;
    QLineEdit *line_timestamp_4;
    QLineEdit *line_path_4;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_save;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLineEdit *line_resolution_y;
    QLineEdit *line_resolution_y_2;
    QLineEdit *line_resolution_x_2;
    QLineEdit *line_resolution_y_3;
    QLineEdit *line_resolution_x_3;
    QLineEdit *line_resolution_y_4;
    QLineEdit *line_resolution_x_4;
    QLabel *label_out;
    QLabel *label_46;
    QLineEdit *line_locality_2;
    QComboBox *comboBox_broth;
    QComboBox *comboBox_broth_2;
    QComboBox *comboBox_broth_3;
    QComboBox *comboBox_broth_4;
    QLineEdit *line_groupID;
    QLineEdit *line_groupID_2;
    QLineEdit *line_groupID_3;
    QLineEdit *line_groupID_4;

    void setupUi(QDialog *multiUpload)
    {
        if (multiUpload->objectName().isEmpty())
            multiUpload->setObjectName(QString::fromUtf8("multiUpload"));
        multiUpload->resize(813, 535);
        buttonBox = new QDialogButtonBox(multiUpload);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setGeometry(QRect(450, 470, 341, 21));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        graphicsView = new QGraphicsView(multiUpload);
        graphicsView->setObjectName(QString::fromUtf8("graphicsView"));
        graphicsView->setGeometry(QRect(10, 140, 191, 171));
        graphicsView_2 = new QGraphicsView(multiUpload);
        graphicsView_2->setObjectName(QString::fromUtf8("graphicsView_2"));
        graphicsView_2->setGeometry(QRect(210, 140, 191, 171));
        graphicsView_3 = new QGraphicsView(multiUpload);
        graphicsView_3->setObjectName(QString::fromUtf8("graphicsView_3"));
        graphicsView_3->setGeometry(QRect(410, 140, 191, 171));
        graphicsView_4 = new QGraphicsView(multiUpload);
        graphicsView_4->setObjectName(QString::fromUtf8("graphicsView_4"));
        graphicsView_4->setGeometry(QRect(610, 140, 191, 171));
        line_groupID_group = new QLineEdit(multiUpload);
        line_groupID_group->setObjectName(QString::fromUtf8("line_groupID_group"));
        line_groupID_group->setGeometry(QRect(90, 30, 113, 20));
        line_genome = new QLineEdit(multiUpload);
        line_genome->setObjectName(QString::fromUtf8("line_genome"));
        line_genome->setGeometry(QRect(300, 30, 113, 20));
        label_22 = new QLabel(multiUpload);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 70, 71, 20));
        line_spore_color = new QLineEdit(multiUpload);
        line_spore_color->setObjectName(QString::fromUtf8("line_spore_color"));
        line_spore_color->setGeometry(QRect(300, 70, 113, 20));
        line_internID = new QLineEdit(multiUpload);
        line_internID->setObjectName(QString::fromUtf8("line_internID"));
        line_internID->setGeometry(QRect(90, 50, 113, 20));
        label_27 = new QLabel(multiUpload);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(220, 70, 71, 20));
        label_21 = new QLabel(multiUpload);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 50, 71, 20));
        label_24 = new QLabel(multiUpload);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(220, 30, 71, 20));
        label_25 = new QLabel(multiUpload);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(220, 50, 71, 20));
        checkBox_siderophore = new QCheckBox(multiUpload);
        checkBox_siderophore->setObjectName(QString::fromUtf8("checkBox_siderophore"));
        checkBox_siderophore->setGeometry(QRect(300, 90, 51, 21));
        label_26 = new QLabel(multiUpload);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(220, 90, 71, 20));
        label_18 = new QLabel(multiUpload);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 10, 71, 16));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_18->setFont(font);
        line_timestamp_group = new QLineEdit(multiUpload);
        line_timestamp_group->setObjectName(QString::fromUtf8("line_timestamp_group"));
        line_timestamp_group->setGeometry(QRect(90, 70, 113, 20));
        label_20 = new QLabel(multiUpload);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 30, 71, 20));
        label_23 = new QLabel(multiUpload);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 90, 81, 20));
        line_locality = new QLineEdit(multiUpload);
        line_locality->setObjectName(QString::fromUtf8("line_locality"));
        line_locality->setGeometry(QRect(300, 50, 53, 20));
        line_scientific = new QLineEdit(multiUpload);
        line_scientific->setObjectName(QString::fromUtf8("line_scientific"));
        line_scientific->setGeometry(QRect(90, 90, 113, 20));
        label_5 = new QLabel(multiUpload);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 323, 71, 20));
        line_ID = new QLineEdit(multiUpload);
        line_ID->setObjectName(QString::fromUtf8("line_ID"));
        line_ID->setGeometry(QRect(80, 320, 113, 20));
        label_10 = new QLabel(multiUpload);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 420, 71, 21));
        label_8 = new QLabel(multiUpload);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 380, 71, 21));
        label_7 = new QLabel(multiUpload);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 360, 71, 21));
        label_6 = new QLabel(multiUpload);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 340, 71, 21));
        line_resolution_x = new QLineEdit(multiUpload);
        line_resolution_x->setObjectName(QString::fromUtf8("line_resolution_x"));
        line_resolution_x->setGeometry(QRect(80, 380, 53, 20));
        label_9 = new QLabel(multiUpload);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 400, 71, 21));
        line_imgSize = new QLineEdit(multiUpload);
        line_imgSize->setObjectName(QString::fromUtf8("line_imgSize"));
        line_imgSize->setGeometry(QRect(80, 360, 113, 20));
        line_timestamp = new QLineEdit(multiUpload);
        line_timestamp->setObjectName(QString::fromUtf8("line_timestamp"));
        line_timestamp->setGeometry(QRect(80, 340, 113, 20));
        line_path = new QLineEdit(multiUpload);
        line_path->setObjectName(QString::fromUtf8("line_path"));
        line_path->setGeometry(QRect(80, 440, 113, 20));
        label_13 = new QLabel(multiUpload);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 440, 71, 21));
        label_14 = new QLabel(multiUpload);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(210, 440, 71, 21));
        line_ID_2 = new QLineEdit(multiUpload);
        line_ID_2->setObjectName(QString::fromUtf8("line_ID_2"));
        line_ID_2->setGeometry(QRect(280, 320, 113, 20));
        label_11 = new QLabel(multiUpload);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(210, 360, 71, 21));
        label_12 = new QLabel(multiUpload);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(210, 400, 71, 21));
        label_15 = new QLabel(multiUpload);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(210, 323, 71, 20));
        line_imgSize_2 = new QLineEdit(multiUpload);
        line_imgSize_2->setObjectName(QString::fromUtf8("line_imgSize_2"));
        line_imgSize_2->setGeometry(QRect(280, 360, 113, 20));
        line_timestamp_2 = new QLineEdit(multiUpload);
        line_timestamp_2->setObjectName(QString::fromUtf8("line_timestamp_2"));
        line_timestamp_2->setGeometry(QRect(280, 340, 113, 20));
        line_path_2 = new QLineEdit(multiUpload);
        line_path_2->setObjectName(QString::fromUtf8("line_path_2"));
        line_path_2->setGeometry(QRect(280, 440, 113, 20));
        label_16 = new QLabel(multiUpload);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(210, 340, 71, 21));
        label_17 = new QLabel(multiUpload);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(210, 420, 71, 21));
        label_19 = new QLabel(multiUpload);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(210, 380, 71, 21));
        label_28 = new QLabel(multiUpload);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(410, 440, 71, 21));
        line_ID_3 = new QLineEdit(multiUpload);
        line_ID_3->setObjectName(QString::fromUtf8("line_ID_3"));
        line_ID_3->setGeometry(QRect(480, 320, 113, 20));
        label_29 = new QLabel(multiUpload);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(410, 360, 71, 21));
        label_30 = new QLabel(multiUpload);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(410, 400, 71, 21));
        label_31 = new QLabel(multiUpload);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(410, 323, 71, 20));
        line_imgSize_3 = new QLineEdit(multiUpload);
        line_imgSize_3->setObjectName(QString::fromUtf8("line_imgSize_3"));
        line_imgSize_3->setGeometry(QRect(480, 360, 113, 20));
        line_timestamp_3 = new QLineEdit(multiUpload);
        line_timestamp_3->setObjectName(QString::fromUtf8("line_timestamp_3"));
        line_timestamp_3->setGeometry(QRect(480, 340, 113, 20));
        line_path_3 = new QLineEdit(multiUpload);
        line_path_3->setObjectName(QString::fromUtf8("line_path_3"));
        line_path_3->setGeometry(QRect(480, 440, 113, 20));
        label_32 = new QLabel(multiUpload);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(410, 340, 71, 21));
        label_33 = new QLabel(multiUpload);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(410, 420, 71, 21));
        label_34 = new QLabel(multiUpload);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(410, 380, 71, 21));
        label_35 = new QLabel(multiUpload);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(610, 440, 71, 21));
        line_ID_4 = new QLineEdit(multiUpload);
        line_ID_4->setObjectName(QString::fromUtf8("line_ID_4"));
        line_ID_4->setGeometry(QRect(680, 320, 113, 20));
        label_36 = new QLabel(multiUpload);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(610, 360, 71, 21));
        label_37 = new QLabel(multiUpload);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(610, 400, 71, 21));
        label_38 = new QLabel(multiUpload);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(610, 323, 71, 20));
        line_imgSize_4 = new QLineEdit(multiUpload);
        line_imgSize_4->setObjectName(QString::fromUtf8("line_imgSize_4"));
        line_imgSize_4->setGeometry(QRect(680, 360, 113, 20));
        line_timestamp_4 = new QLineEdit(multiUpload);
        line_timestamp_4->setObjectName(QString::fromUtf8("line_timestamp_4"));
        line_timestamp_4->setGeometry(QRect(680, 340, 113, 20));
        line_path_4 = new QLineEdit(multiUpload);
        line_path_4->setObjectName(QString::fromUtf8("line_path_4"));
        line_path_4->setGeometry(QRect(680, 440, 113, 20));
        label_39 = new QLabel(multiUpload);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(610, 340, 71, 21));
        label_40 = new QLabel(multiUpload);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(610, 420, 71, 21));
        label_41 = new QLabel(multiUpload);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(610, 380, 71, 21));
        pushButton = new QPushButton(multiUpload);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(120, 120, 81, 21));
        pushButton_2 = new QPushButton(multiUpload);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(320, 120, 81, 21));
        pushButton_3 = new QPushButton(multiUpload);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(520, 120, 81, 21));
        pushButton_4 = new QPushButton(multiUpload);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(720, 120, 81, 21));
        pushButton_save = new QPushButton(multiUpload);
        pushButton_save->setObjectName(QString::fromUtf8("pushButton_save"));
        pushButton_save->setGeometry(QRect(550, 470, 75, 21));
        label_42 = new QLabel(multiUpload);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(10, 120, 41, 16));
        label_42->setFont(font);
        label_43 = new QLabel(multiUpload);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(210, 120, 31, 16));
        label_43->setFont(font);
        label_44 = new QLabel(multiUpload);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(410, 120, 51, 16));
        label_44->setFont(font);
        label_45 = new QLabel(multiUpload);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(610, 120, 31, 16));
        label_45->setFont(font);
        line_resolution_y = new QLineEdit(multiUpload);
        line_resolution_y->setObjectName(QString::fromUtf8("line_resolution_y"));
        line_resolution_y->setGeometry(QRect(140, 380, 53, 20));
        line_resolution_y_2 = new QLineEdit(multiUpload);
        line_resolution_y_2->setObjectName(QString::fromUtf8("line_resolution_y_2"));
        line_resolution_y_2->setGeometry(QRect(340, 380, 53, 20));
        line_resolution_x_2 = new QLineEdit(multiUpload);
        line_resolution_x_2->setObjectName(QString::fromUtf8("line_resolution_x_2"));
        line_resolution_x_2->setGeometry(QRect(280, 380, 53, 20));
        line_resolution_y_3 = new QLineEdit(multiUpload);
        line_resolution_y_3->setObjectName(QString::fromUtf8("line_resolution_y_3"));
        line_resolution_y_3->setGeometry(QRect(540, 380, 53, 20));
        line_resolution_x_3 = new QLineEdit(multiUpload);
        line_resolution_x_3->setObjectName(QString::fromUtf8("line_resolution_x_3"));
        line_resolution_x_3->setGeometry(QRect(480, 380, 53, 20));
        line_resolution_y_4 = new QLineEdit(multiUpload);
        line_resolution_y_4->setObjectName(QString::fromUtf8("line_resolution_y_4"));
        line_resolution_y_4->setGeometry(QRect(740, 380, 53, 20));
        line_resolution_x_4 = new QLineEdit(multiUpload);
        line_resolution_x_4->setObjectName(QString::fromUtf8("line_resolution_x_4"));
        line_resolution_x_4->setGeometry(QRect(680, 380, 53, 20));
        label_out = new QLabel(multiUpload);
        label_out->setObjectName(QString::fromUtf8("label_out"));
        label_out->setGeometry(QRect(550, 500, 241, 21));
        label_46 = new QLabel(multiUpload);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(420, 50, 111, 20));
        line_locality_2 = new QLineEdit(multiUpload);
        line_locality_2->setObjectName(QString::fromUtf8("line_locality_2"));
        line_locality_2->setGeometry(QRect(360, 50, 53, 20));
        comboBox_broth = new QComboBox(multiUpload);
        comboBox_broth->setObjectName(QString::fromUtf8("comboBox_broth"));
        comboBox_broth->setGeometry(QRect(80, 400, 113, 20));
        comboBox_broth_2 = new QComboBox(multiUpload);
        comboBox_broth_2->setObjectName(QString::fromUtf8("comboBox_broth_2"));
        comboBox_broth_2->setGeometry(QRect(280, 400, 113, 20));
        comboBox_broth_3 = new QComboBox(multiUpload);
        comboBox_broth_3->setObjectName(QString::fromUtf8("comboBox_broth_3"));
        comboBox_broth_3->setGeometry(QRect(480, 400, 113, 20));
        comboBox_broth_4 = new QComboBox(multiUpload);
        comboBox_broth_4->setObjectName(QString::fromUtf8("comboBox_broth_4"));
        comboBox_broth_4->setGeometry(QRect(680, 400, 113, 20));
        line_groupID = new QLineEdit(multiUpload);
        line_groupID->setObjectName(QString::fromUtf8("line_groupID"));
        line_groupID->setGeometry(QRect(80, 420, 113, 20));
        line_groupID_2 = new QLineEdit(multiUpload);
        line_groupID_2->setObjectName(QString::fromUtf8("line_groupID_2"));
        line_groupID_2->setGeometry(QRect(280, 420, 113, 20));
        line_groupID_3 = new QLineEdit(multiUpload);
        line_groupID_3->setObjectName(QString::fromUtf8("line_groupID_3"));
        line_groupID_3->setGeometry(QRect(480, 420, 113, 20));
        line_groupID_4 = new QLineEdit(multiUpload);
        line_groupID_4->setObjectName(QString::fromUtf8("line_groupID_4"));
        line_groupID_4->setGeometry(QRect(680, 420, 113, 20));

        retranslateUi(multiUpload);
        QObject::connect(buttonBox, SIGNAL(accepted()), multiUpload, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), multiUpload, SLOT(reject()));
        QObject::connect(pushButton, SIGNAL(clicked()), multiUpload, SLOT(selectFile1()));
        QObject::connect(pushButton_2, SIGNAL(clicked()), multiUpload, SLOT(selectFile2()));
        QObject::connect(pushButton_3, SIGNAL(clicked()), multiUpload, SLOT(selectFile3()));
        QObject::connect(pushButton_4, SIGNAL(clicked()), multiUpload, SLOT(selectFile4()));
        QObject::connect(pushButton_save, SIGNAL(clicked()), multiUpload, SLOT(saveAll()));

        QMetaObject::connectSlotsByName(multiUpload);
    } // setupUi

    void retranslateUi(QDialog *multiUpload)
    {
        multiUpload->setWindowTitle(QApplication::translate("multiUpload", "StreptoDB", nullptr));
        label_22->setText(QApplication::translate("multiUpload", "Timestamp:", nullptr));
        label_27->setText(QApplication::translate("multiUpload", "Spore-Color:", nullptr));
        label_21->setText(QApplication::translate("multiUpload", "Intern-ID:", nullptr));
        label_24->setText(QApplication::translate("multiUpload", "Genome-Link:", nullptr));
        label_25->setText(QApplication::translate("multiUpload", "Locality:", nullptr));
        checkBox_siderophore->setText(QString());
        label_26->setText(QApplication::translate("multiUpload", "Siderophore:", nullptr));
        label_18->setText(QApplication::translate("multiUpload", "Group Info:", nullptr));
        label_20->setText(QApplication::translate("multiUpload", "Group-ID:", nullptr));
        label_23->setText(QApplication::translate("multiUpload", "Scientific-Name:", nullptr));
        label_5->setText(QApplication::translate("multiUpload", "ID:", nullptr));
        label_10->setText(QApplication::translate("multiUpload", "Group ID:", nullptr));
        label_8->setText(QApplication::translate("multiUpload", "Resol. x/y:", nullptr));
        label_7->setText(QApplication::translate("multiUpload", "Imagesize:", nullptr));
        label_6->setText(QApplication::translate("multiUpload", "Timestamp:", nullptr));
        label_9->setText(QApplication::translate("multiUpload", "Broth:", nullptr));
        label_13->setText(QApplication::translate("multiUpload", "Path:", nullptr));
        label_14->setText(QApplication::translate("multiUpload", "Path:", nullptr));
        label_11->setText(QApplication::translate("multiUpload", "Imagesize:", nullptr));
        label_12->setText(QApplication::translate("multiUpload", "Broth:", nullptr));
        label_15->setText(QApplication::translate("multiUpload", "ID:", nullptr));
        label_16->setText(QApplication::translate("multiUpload", "Timestamp:", nullptr));
        label_17->setText(QApplication::translate("multiUpload", "Group ID:", nullptr));
        label_19->setText(QApplication::translate("multiUpload", "Resol. x/y:", nullptr));
        label_28->setText(QApplication::translate("multiUpload", "Path:", nullptr));
        label_29->setText(QApplication::translate("multiUpload", "Imagesize:", nullptr));
        label_30->setText(QApplication::translate("multiUpload", "Broth:", nullptr));
        label_31->setText(QApplication::translate("multiUpload", "ID:", nullptr));
        label_32->setText(QApplication::translate("multiUpload", "Timestamp:", nullptr));
        label_33->setText(QApplication::translate("multiUpload", "Group ID:", nullptr));
        label_34->setText(QApplication::translate("multiUpload", "Resol. x/y:", nullptr));
        label_35->setText(QApplication::translate("multiUpload", "Path:", nullptr));
        label_36->setText(QApplication::translate("multiUpload", "Imagesize:", nullptr));
        label_37->setText(QApplication::translate("multiUpload", "Broth:", nullptr));
        label_38->setText(QApplication::translate("multiUpload", "ID:", nullptr));
        label_39->setText(QApplication::translate("multiUpload", "Timestamp:", nullptr));
        label_40->setText(QApplication::translate("multiUpload", "Group ID:", nullptr));
        label_41->setText(QApplication::translate("multiUpload", "Resol. x/y:", nullptr));
        pushButton->setText(QApplication::translate("multiUpload", "Select...", nullptr));
        pushButton_2->setText(QApplication::translate("multiUpload", "Select...", nullptr));
        pushButton_3->setText(QApplication::translate("multiUpload", "Select...", nullptr));
        pushButton_4->setText(QApplication::translate("multiUpload", "Select...", nullptr));
        pushButton_save->setText(QApplication::translate("multiUpload", "Save", nullptr));
        label_42->setText(QApplication::translate("multiUpload", "ISP2:", nullptr));
        label_43->setText(QApplication::translate("multiUpload", "GN:", nullptr));
        label_44->setText(QApplication::translate("multiUpload", "NCBMM:", nullptr));
        label_45->setText(QApplication::translate("multiUpload", "SFM:", nullptr));
        label_out->setText(QApplication::translate("multiUpload", "...", nullptr));
        label_46->setText(QApplication::translate("multiUpload", "Latitude / Longitude", nullptr));
    } // retranslateUi

};

namespace Ui {
    class multiUpload: public Ui_multiUpload {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MULTIUPLOADDIALOG_H
